### ISSUE TITLE
Sqlup mode break highlighting when disabled in buffer

### ISSUE THREAD

**Issue by kepi** [Trevoke/sqlup-mode.el#63]
Hi,

I'm trying to integrate `sqlup-mode` in spacemacs's `sql` layer syl20bnr/spacemacs#7789

### Actual behavior

While I want to add toggle option - I discovered that if you call `sqlup-mode` when minor is already enabled it disables itself - as it should - but it also "break" sql mode. At least higlighting "dissapears".

### Desired behavior

Desired behaviour is to just disable `sqlup-mode` minor when executing `sqlup-mode` while active.

**Comment by Trevoke** [comment]
I'm currently unable to replicate this problem.

I need a little bit more information:

What OS are you using?
What distribution of emacs are you using?
What version of sqlup-mode are you using?
What major mode is it? I'm guessing `sql-mode`; if it is, then do you know which flavor of SQL you have enabled?

If spacemacs has such a thing as "versions", what version of spacemacs are you using?

**Comment by Trevoke** [comment]
Also - I currently don't use spacemacs. If I want to try and replicate exactly your problem, can you help me figure out how to replicate what you're doing with spacemacs -- that is, what I need to do beyond adding the sql layer?

**Comment by kepi** [comment]
Debian GNU/Linux unstable, distribution is spacemacs (develop version) with latest sqlup-mode. Major is `sql-mode` with `postgresql` behaviour.

I think it should be enough if you add `sql` layer and add `sqlup-mode` to additional packages. Anyway I can test it in clear environment and tell you exactly how to reproduce if it isn't easily reproducable now. It may be error somewhere else in my config or layer if it is working for you.

**Comment by Trevoke** [comment]
I'm unable to replicate right now.

I'm on Ubuntu 16.04 LTS.

spacemacs-version: 0.200.5
emacs-version: 24.5.1

I told spacemacs I wanted the default config, not the minimalist one.
I also said I wanted ivy, not helm.
I put `sql` inside `dotspacemacs-configuration-layers`.
I added `sqlup-mode` inside `dotspacemacs-additional-packages`

I tried to open a SQL file, enable sqlup-mode, type, disable sqlup-mode.

I tried to open `sql-postgres`, enable sqlup-mode, type, disable sqlup-mode.

In both cases, font locking behavior did not break.

**Comment by Trevoke** [comment]
Any updates on your side about this?

**Comment by davidshepherd7** [comment]
I've reproduced this in sqlup-mode versions 20160904.838 and 20160911.1911, on emacs 25.1, Ubuntu 14.04 without spacemacs (or anything else) with the following steps:

```
emacs -Q some-sql-file.sql -l ~/.emacs.d/elpa/sqlup-mode-20160904.838/sqlup-mode.el
M-x sqlup-mode
M-x sqlup-mode
```

I get the error message `Not enabling jit-lock: it does not work in indirect buffer` and font-lock stops working (although `font-lock` mode is still enabled).

Not got time to have a dig right now, but maybe sometime this week...

**Comment by Trevoke** [comment]
Okay -- that's reproduced! Thanks for taking the time to make it reproducible.
Now to fix it. 
Off-hand, I can think of two ways:
1. I suspect that doing the work for #48 should make this problem go away. That's the preferred fix for me as far as the long-term vision for this package.
2. There's probably some additional logic we can place in the `defadvice font-lock-mode` to make sure it doesn't try to do something stupid like this. This might be less work and would be good to learn about for me.

The reason you're getting this `jit-lock` message is because of trouble I ran into with the creation of a cloned indirect buffer where I change the major mode to `sql-mode`. You can read more about it here: https://github.com/Trevoke/sqlup-mode.el/blob/master/sqlup-mode.el#L254

**Comment by kepi** [comment]
@Trevoke sorry, didn't have time yet but  @davidshepherd7 comment got me one idea.

I don't have this problem in normal SQL[ANSI] buffer but only when I'm editting SQL code in org-mode in its own code buffer `C-c '`

> C-c ' for editing the current code block. It opens a new major-mode edit buffer containing the body of the source code block, ready for any edits. C-c ' again to close the buffer and return to the Org buffer.

btw. I'm getting `jit-lock` message even when it works (in normal buffer).

**Comment by Trevoke** [comment]
Okay, try the next version, as far as I can tell I fixed it.

I really had no idea how to write a test for this, because as far as I can tell, it's kind of a bug with emacs, and kind of because indirect buffers are a bit of a horrid hack if you actually do anything with them like I am.

**Comment by davidshepherd7** [comment]
Yep, seems to have fixed it for me :+1:

**Comment by Trevoke** [comment]
Awesome! Now if by chance you have any idea how to test this... :) I mean,
write a test for it. All ideas welcome.

**Comment by davidshepherd7** [comment]
I don't really understand why font-lock was being disabled, but if it was just because that error occurred then all you need to do is toggle sqlup-mode on and off again and check that no error occurs.

Or if you wanted to test directly that syntax highlighting is still working: espuds has a step definition for `Then current point should have the \([-[:alnum:]]+\) face` which you could probably use to test that `SELECT` still has the correct highlighting after toggling sqlup.

**Comment by Trevoke** [comment]
The problem isn't that font lock is off but that it disappears. It's still
enabled. I think it might be an emacs bug.

**Comment by davidshepherd7** [comment]
I gave it a try and it's all just awful!

Problem 1 is that font lock doesn't normally run in ecukes tests, you have to use `--no-win` (which runs an interactive emacs in a terminal) or `--win` (which opens a frame). Either of these makes CI and scripting of tests more complicated.

Problem 2 is that the highlighting is only broken for one cycle of jit-lock, and jit-lock can run at any time based on a whole bunch of factors. ecukes gets around the unpredictability by forcing re-fontification before doing any font based assertions, meaning that the problem is always gone by the time any ecukes assertion runs!

It's reasonably straightforward to write a test that checks for an (error) message matching `.*jit-lock.*`, but because of problem 1 it's tricky to run the test.

Problem 2 seems to make it almost impossible to check the actual highlighting without writing your own custom testing infrastructure.

I'm giving up on this now, I don't think it's possible with any reasonable amount of effort :disappointed:

**Comment by Trevoke** [comment]
Thanks for investigating, I appreciate it :) for now I'll just put
something in the "contributing" section indicating to please manually test
this if contributing to sqlup.
