### ISSUE TITLE
if sqlup is hooked to a major mode, the first word might get upcased

### ISSUE THREAD

**Issue by Trevoke** [Trevoke/sqlup-mode.el#65]
sqlup shouldn't modify an existing file when the buffer is loaded; there is code that gets executed on buffer init / major mode init / minor mode init / somewhere around there.. And that code shouldn't be executed.

Version: 0.7.1

**Comment by davidshepherd7** [comment]
I think the problem is that `sqlup-should-do-work-p` checks if the last command was `sqlup-mode` but not for other things like `sql-mode`.

We might be able to do it using `post-self-insert-hook` instead, depends exactly what the intended behaviour for the return keypress is...

I'll have a play now and see if I can come up with a simple pull request.

**Comment by Trevoke** [comment]
Fixed in #66
